device:
  gpu: True
  cuda: [0]

seed: 46
sampling_rate: 8000

HyperParams:
  C: 2
  N: 512
  L: 16
  B: 128
  H: 512
  Sc: 128
  P: 3
  X: 8
  R: 3
  encoder_activate: ReLU
  mask_activate: sigmoid
  causal: False

dataloader:
  batch_size: 3
  num_workers: 20
  shuffule: true

optimizer:
  name: Adam
  HyperParams:
    lr: 1.0e-3
    weight_decay: 0

resume:
  state: False
  path: ./checkpoint/xxx/last.pt
  load_optim: True

stop:
  early_stop: 10
  max_epoch: 100
